2022/07/27 12:12:41 [error] 242386#0: *3 connect() to [2606:2800:220:1:248:1893:25c8:1946]:443 failed (101: Network is unreachable), client: 127.0.0.1, server: , request: "GET / HTTP/1.1", host: "example.com"
2022/07/27 12:12:41 [error] 242386#0: *3 [lua] openidc.lua:567: openidc_discover(): accessing discovery url (https://example.com/.well-known/openid-configuration) failed: network is unreachable, client: 127.0.0.1, server: , request: "GET / HTTP/1.1", host: "example.com"
2022/07/27 12:12:41 [alert] 242386#0: *3 ignoring stale global SSL error (SSL: error:06065064:digital envelope routines:EVP_DecryptFinal_ex:bad decrypt), client: 127.0.0.1, server: , request: "GET / HTTP/1.1", host: "example.com"
2022/07/27 12:12:41 [error] 242386#0: *3 connect() to [2606:2800:220:1:248:1893:25c8:1946]:443 failed (101: Network is unreachable), client: 127.0.0.1, server: , request: "GET /favicon.ico HTTP/1.1", host: "example.com", referrer: "https://example.com/"
2022/07/27 12:12:41 [error] 242386#0: *3 [lua] openidc.lua:567: openidc_discover(): accessing discovery url (https://example.com/.well-known/openid-configuration) failed: network is unreachable, client: 127.0.0.1, server: , request: "GET /favicon.ico HTTP/1.1", host: "example.com", referrer: "https://example.com/"
